### ISSUE TITLE
Some questions regarding functionality

### ISSUE THREAD

**Issue by xosxos** [tedil/rust-bcf#1]
The basics seem to work very well but I stumbled upon some questions pretty quickly !

I am trying this out but I can't figure out how do I extract sample names from the header?

Also all my genotypes have binary data but I see ```Int32([2, 5])``` and ```Int32([2, 3])``` and ```Int32([4, 5])``` when printing the ```Vec<TypedVec>``` from the field ```format``` of the ```BcfRecord```.  I assume this is some way of representing the genotypes as ```0|1 1/1... etc``` values?

**Comment by tedil** [comment]
When I initially wrote this, I worked my way through the VCF/BCF specification, so most of the interface is really bare-bones. I'd be glad if we could improve that!

For the genotype (i.e. `FORMAT/GT`): The [specification](https://samtools.github.io/hts-specs/VCFv4.3.pdf) on the lower half of page 32 tells us how to interpret these values. This shouldn't be too hard to add ;)
Note that genotype fields such as GT are not encoded per-sample i.e. not as Sample1:0/1, Sample2: 0/0, Sample3: 1/0 but grouped by field, i.e. GT:0/1,0/0,1/0.

As for the sample names: I'm currently re-reading the specification and trying to find where they are specified, since most strings are just encoded as offsets into or IDs in the header. But I can't really find anything about that, so I suspect we'll just have to parse the (pain-text) header line `"#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSample1\tSample2\t...\n\u{0}"` and assume the order of samples in that line matches the order of samples as used in the FORMAT encoding.

P.S.: I suggest using the lazy-records branch, which provides`RawBcfRecords`, which yields `RawBcfRecord`s which do the actual parsing (from raw bytes to something interpreted) on-demand instead of eagerly (since most of the time only parts of the record are really of interest; this also, in my preliminary benchmarking, makes it faster than rust-htslib)

*edit*: I added the samples by parsing them from the `#CHROM\t...` line, see test in `lib.rs`, just a quick fix, but at least we have the sample names now ;)

**Comment by tedil** [comment]
So, for genotypes, something like:
```rust
use rust_bcf::reader::RawBcfRecords as BcfRecords;
use rust_bcf::record::Record;

let records = BcfRecords::from_path("resources/example.uncompressed.bcf")?;
for record in records {
    // one genotype per sample
    let genotypes = record
        .format(b"GT")
        .map(|samples| {
            // remember that the internal representation is: `GT:data for sample1,data for sample2,...,data for sample n`
            samples
                .iter()
                .map(|gt| {
                    // constructing a genotype String for demonstration purposes
                    let mut genotype = String::new();
                    for (allele, value) in gt.integer().iter().enumerate() {
                        let phased = (value & 1) != 0;
                        let val = (value >> 1) - 1;
                        if allele > 0 {
                            genotype.push(if phased { '|' } else { '/' });
                        }
                        genotype += &format!("{}", val);
                    }
                    genotype
                })
                .collect::<Vec<_>>()
        })
        .unwrap();
    println!("{:?}", &genotypes);
}
```
should do the trick.
However, we should probably have a convenience function for that, such as `record.genotype(sample)` (but not with Strings, of course.)

**Comment by xosxos** [comment]
Yess the samples are working now, thank you ! Although its a private field when accessing from outside the crate.

And about workflows and convenience I usually start by storing everything into ```ndarray```. So ```record.genotypes()```that returns the genotypes in a more human readable format would be nice to have. ```rust-htslib``` has the enum ```GenotypeAllele``` so maybe generate a ```Vec<Vec<GenotypeAllele>>``` from the ```Vec<TypedVec>``` ? Altought I have just begun to dip my toes into Rust bioinformatics so I am way out of my comfort zone :0

```rust
use ndarray::{Array3, s};

// Storing phased binary genotype data into a 3-dimensional array
let mut matrix = Array3::<i32>::from_elem((2, sample_n, records_n), 0);

for (record_i, record) in records.enumerate() {
    for (sample_i, gt) in record.genotypes().iter().enumerate() {
        for (allele_i, value) in gt.integer().iter().enumerate() {
            let val = (value >> 1) - 1;
            match allele_i {
                0 | 1 => matrix.slice_mut(s![allele_i, sample_i, record_i]).fill(val),
                _ => panic!(),
            };
         }
     }
 } 
```
However one major problem with this is that the array is not created dynamically so I need to know beforehand how many records there are in the vcf/bcf. And as ```.count()``` consumes an iterator this becomes  bit tricky...

**Comment by tedil** [comment]
> Yess the samples are working now, thank you ! Although its a private field when accessing from outside the crate.
> 
> And about workflows and convenience I usually start by storing everything into `ndarray`. So `record.genotypes()`that returns the genotypes in a more human readable format would be nice to have. `rust-htslib` has the enum `GenotypeAllele` so maybe generate a `Vec<Vec<GenotypeAllele>>` from the `Vec<TypedVec>` ? Altought I have just begun to dip my toes into Rust bioinformatics so I am way out of my comfort zone :0
> 

Having an API similar to either or both rust-htslib / rust-bio is what I am after, anyways ;)

> ```rust
> use ndarray::{Array3, s};
> 
> // Storing phased binary genotype data into a 3-dimensional array
> let mut matrix = Array3::<i32>::from_elem((2, sample_n, records_n), 0);
> 
> for (record_i, record) in records.enumerate() {
>     for (sample_i, gt) in record.genotypes().iter().enumerate() {
>         for (allele_i, value) in gt.integer().iter().enumerate() {
>             let val = (value >> 1) - 1;
>             match allele_i {
>                 0 | 1 => matrix.slice_mut(s![allele_i, sample_i, record_i]).fill(val),
>                 _ => panic!(),
>             };
>          }
>      }
>  } 
> ```
> 
> However one major problem with this is that the array is not created dynamically so I need to know beforehand how many records there are in the vcf/bcf. And as `.count()` consumes an iterator this becomes bit tricky...

Since you don't know how many records there will be, you'd probably just collect everything into a vector and go from there (e.g. construct the 3D array once you have the data for all records, if you really need the 3D array downstream)

**Comment by xosxos** [comment]
Yeah I think its faster and more effective to create two matrices from two vecs and then stack them in need but the code does not look that nice :(

Speaking of looking nice ```Vec<Vec<GenotypeAllele>>``` is not that suave either. Played around a bit with the ```genotypes``` method using ```.fold()``` for fun. But did not get into how missing data is coded into the standard. And I dont think the phased boolean is working correctly in this bit of code either.

```rust
#[derive(Debug)]
pub enum GenotypeAllele {
    Unphased(i32),
    Phased(i32),
    UnphasedMissing,
    PhasedMissing,
}
impl Record for RawBcfRecord {
   fn genotypes(&self) -> Vec<Vec<GenotypeAllele>> {
        self.format(b"GT")
            .unwrap()
            .iter()
            .map(|gts| {
                gts.integer().iter().fold(vec![], |mut genotype, value| {
                    let phased = (value & 1) != 0;
                    let val = (value >> 1) - 1;
                    let g = match phased {
                        true => GenotypeAllele::Phased(val),
                        false => GenotypeAllele::Unphased(val),
                    };
                    genotype.push(g);
                    genotype
                })
            })
            .collect::<Vec<_>>()
    }
}
```

**Comment by tedil** [comment]
See https://github.com/tedil/rust-bcf/blob/4dc4f9d236fa6412908b97787496edeb7bd431fd/src/record.rs#L244  and  https://github.com/tedil/rust-bcf/blob/4dc4f9d236fa6412908b97787496edeb7bd431fd/src/record.rs#L269
